# Lab | Data Structuring and Combining Data

## Challenge 1: Combining & Cleaning Data

In this challenge, we will be working with the customer data from an insurance company, as we did in the two previous labs. The data can be found here:
- https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file1.csv

But this time, we got new data, which can be found in the following 2 CSV files located at the links below.

- https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file2.csv
- https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file3.csv

Note that you'll need to clean and format the new data.

Observation:
- One option is to first combine the three datasets and then apply the cleaning function to the new combined dataset
- Another option would be to read the clean file you saved in the previous lab, and just clean the two new files and concatenate the three clean datasets

In [1]:
import pandas as pd

df1 = pd.read_csv("https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file1.csv")
df2 = pd.read_csv("https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file2.csv")
df3 = pd.read_csv("https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file3.csv")

In [2]:
df1

,Customer,ST,GENDER,Education,Customer Lifetime Value,Income,Monthly Premium Auto,Number of Open Complaints,Policy Type,Vehicle Class,Total Claim Amount
0,RB50392,Washington,NaN,Master,NaN,0.0,1000.0,1/0/00,Personal Auto,Four-Door Car,2.704934
1,QZ44356,Arizona,F,Bachelor,697953.59%,0.0,94.0,1/0/00,Personal Auto,Four-Door Car,1131.464935
2,AI49188,Nevada,F,Bachelor,1288743.17%,48767.0,108.0,1/0/00,Personal Auto,Two-Door Car,566.472247
3,WW63253,California,M,Bachelor,764586.18%,0.0,106.0,1/0/00,Corporate Auto,SUV,529.881344
4,GA49547,Washington,M,High School or Below,536307.65%,36357.0,68.0,1/0/00,Personal Auto,Four-Door Car,17.269323
...,...,...,...,...,...,...,...,...,...,...,...
4003,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4004,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4005,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4006,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4007,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
df2

,Customer,ST,GENDER,Education,Customer Lifetime Value,Income,Monthly Premium Auto,Number of Open Complaints,Total Claim Amount,Policy Type,Vehicle Class
0,GS98873,Arizona,F,Bachelor,323912.47%,16061,88,1/0/00,633.600000,Personal Auto,Four-Door Car
1,CW49887,California,F,Master,462680.11%,79487,114,1/0/00,547.200000,Special Auto,SUV
2,MY31220,California,F,College,899704.02%,54230,112,1/0/00,537.600000,Personal Auto,Two-Door Car
3,UH35128,Oregon,F,College,2580706.30%,71210,214,1/1/00,1027.200000,Personal Auto,Luxury Car
4,WH52799,Arizona,F,College,380812.21%,94903,94,1/0/00,451.200000,Corporate Auto,Two-Door Car
...,...,...,...,...,...,...,...,...,...,...,...
991,HV85198,Arizona,M,Master,847141.75%,63513,70,1/0/00,185.667213,Personal Auto,Four-Door Car
992,BS91566,Arizona,F,College,543121.91%,58161,68,1/0/00,140.747286,Corporate Auto,Four-Door Car
993,IL40123,Nevada,F,College,568964.41%,83640,70,1/0/00,471.050488,Corporate Auto,Two-Door Car
994,MY32149,California,F,Master,368672.38%,0,96,1/0/00,28.460568,Personal Auto,Two-Door Car
995,SA91515,California,M,Bachelor,399258.39%,0,111,1/0/00,700.349052,Personal Auto,SUV

In [4]:
df3

,Customer,State,Customer Lifetime Value,Education,Gender,Income,Monthly Premium Auto,Number of Open Complaints,Policy Type,Total Claim Amount,Vehicle Class
0,SA25987,Washington,3479.137523,High School or Below,M,0,104,0,Personal Auto,499.200000,Two-Door Car
1,TB86706,Arizona,2502.637401,Master,M,0,66,0,Personal Auto,3.468912,Two-Door Car
2,ZL73902,Nevada,3265.156348,Bachelor,F,25820,82,0,Personal Auto,393.600000,Four-Door Car
3,KX23516,California,4455.843406,High School or Below,F,0,121,0,Personal Auto,699.615192,SUV
4,FN77294,California,7704.958480,High School or Below,M,30366,101,2,Personal Auto,484.800000,SUV
...,...,...,...,...,...,...,...,...,...,...,...
7065,LA72316,California,23405.987980,Bachelor,M,71941,73,0,Personal Auto,198.234764,Four-Door Car
7066,PK87824,California,3096.511217,College,F,21604,79,0,Corporate Auto,379.200000,Four-Door Car
7067,TD14365,California,8163.890428,Bachelor,M,0,85,3,Corporate Auto,790.784983,Four-Door Car
7068,UP19263,California,7524.442436,College,M,21941,96,0,Personal Auto,691.200000,Four-Door Car
7069,Y167826,California,2611.836866,College,M,0,77,0,Corporate Auto,369.600000,Two-Door Car

In [5]:
df1.rename(columns={'ST': 'State', 'GENDER': 'Gender'}, inplace=True)
df2.rename(columns={'ST': 'State', 'GENDER': 'Gender'}, inplace=True)

df1.dropna(how='all', inplace=True)
df2.dropna(how='all', inplace=True)
df3.dropna(how='all', inplace=True)

df1['Number of Open Complaints'] = (df1['Number of Open Complaints'].str.split('/').str[0].apply(pd.to_numeric, errors='coerce').astype('int'))
df2['Number of Open Complaints'] = (df2['Number of Open Complaints'].str.split('/').str[0].apply(pd.to_numeric, errors='coerce').astype('int'))

df1['Customer Lifetime Value'] = df1['Customer Lifetime Value'].str.rstrip('%').astype('float') / 100
df2['Customer Lifetime Value'] = df2['Customer Lifetime Value'].str.rstrip('%').astype('float') / 100

In [6]:
df = pd.concat([df1, df2, df3], ignore_index=True)
df

,Customer,State,Gender,Education,Customer Lifetime Value,Income,Monthly Premium Auto,Number of Open Complaints,Policy Type,Vehicle Class,Total Claim Amount
0,RB50392,Washington,NaN,Master,NaN,0.0,1000.0,1,Personal Auto,Four-Door Car,2.704934
1,QZ44356,Arizona,F,Bachelor,6979.535900,0.0,94.0,1,Personal Auto,Four-Door Car,1131.464935
2,AI49188,Nevada,F,Bachelor,12887.431700,48767.0,108.0,1,Personal Auto,Two-Door Car,566.472247
3,WW63253,California,M,Bachelor,7645.861800,0.0,106.0,1,Corporate Auto,SUV,529.881344
4,GA49547,Washington,M,High School or Below,5363.076500,36357.0,68.0,1,Personal Auto,Four-Door Car,17.269323
...,...,...,...,...,...,...,...,...,...,...,...
9132,LA72316,California,M,Bachelor,23405.987980,71941.0,73.0,0,Personal Auto,Four-Door Car,198.234764
9133,PK87824,California,F,College,3096.511217,21604.0,79.0,0,Corporate Auto,Four-Door Car,379.200000
9134,TD14365,California,M,Bachelor,8163.890428,0.0,85.0,3,Corporate Auto,Four-Door Car,790.784983
9135,UP19263,California,M,College,7524.442436,21941.0,96.0,0,Personal Auto,Four-Door Car,691.200000
9136,Y167826,California,M,College,2611.836866,0.0,77.0,0,Corporate Auto,Two-Door Car,369.600000

In [7]:
state_mapping = {'Cali': 'CA', 'California': 'CA', 'Arizona': 'AZ', 'Washington': 'WA', 'Nevada': 'NV', 'Oregon': 'OR'}
df['State'] = df['State'].replace(state_mapping)

gender_mapping = {'Femal': 'F', 'female': 'F', 'Male': 'M'}
df['Gender'] = df['Gender'].replace(gender_mapping)

df = df.drop_duplicates()

df

,Customer,State,Gender,Education,Customer Lifetime Value,Income,Monthly Premium Auto,Number of Open Complaints,Policy Type,Vehicle Class,Total Claim Amount
0,RB50392,WA,NaN,Master,NaN,0.0,1000.0,1,Personal Auto,Four-Door Car,2.704934
1,QZ44356,AZ,F,Bachelor,6979.535900,0.0,94.0,1,Personal Auto,Four-Door Car,1131.464935
2,AI49188,NV,F,Bachelor,12887.431700,48767.0,108.0,1,Personal Auto,Two-Door Car,566.472247
3,WW63253,CA,M,Bachelor,7645.861800,0.0,106.0,1,Corporate Auto,SUV,529.881344
4,GA49547,WA,M,High School or Below,5363.076500,36357.0,68.0,1,Personal Auto,Four-Door Car,17.269323
...,...,...,...,...,...,...,...,...,...,...,...
9132,LA72316,CA,M,Bachelor,23405.987980,71941.0,73.0,0,Personal Auto,Four-Door Car,198.234764
9133,PK87824,CA,F,College,3096.511217,21604.0,79.0,0,Corporate Auto,Four-Door Car,379.200000
9134,TD14365,CA,M,Bachelor,8163.890428,0.0,85.0,3,Corporate Auto,Four-Door Car,790.784983
9135,UP19263,CA,M,College,7524.442436,21941.0,96.0,0,Personal Auto,Four-Door Car,691.200000
9136,Y167826,CA,M,College,2611.836866,0.0,77.0,0,Corporate Auto,Two-Door Car,369.600000

In [8]:
df.sort_values(by='Customer', ignore_index=True)

,Customer,State,Gender,Education,Customer Lifetime Value,Income,Monthly Premium Auto,Number of Open Complaints,Policy Type,Vehicle Class,Total Claim Amount
0,AA10041,CA,M,High School or Below,7901.744238,0.0,113.0,0,Personal Auto,SUV,1258.327804
1,AA11235,NV,F,Bachelor,2568.843396,11167.0,73.0,3,Personal Auto,Two-Door Car,350.400000
2,AA16582,WA,M,Bachelor,24127.504020,14072.0,71.0,0,Personal Auto,Four-Door Car,511.200000
3,AA30683,CA,M,Bachelor,6595.101921,0.0,105.0,2,Personal Auto,Four-Door Car,847.717402
4,AA34092,CA,M,College,28799.954150,33635.0,240.0,0,Personal Auto,Luxury SUV,1152.000000
...,...,...,...,...,...,...,...,...,...,...,...
9129,ZZ77357,NV,M,High School or Below,4468.220900,0.0,65.0,0,Corporate Auto,Two-Door Car,468.000000
9130,ZZ83340,OR,F,Doctor,5508.315500,96021.0,68.0,1,Personal Auto,Two-Door Car,315.004602
9131,ZZ89380,OR,F,Bachelor,3196.578455,62815.0,80.0,0,Special Auto,Two-Door Car,47.061469
9132,ZZ91716,CA,F,Bachelor,3256.766400,0.0,89.0,1,Personal Auto,Four-Door Car,491.755368
9133,ZZ97035,CA,M,College,20714.940400,0.0,203.0,1,Corporate Auto,Luxury Car,2027.724442

In [9]:
df.to_excel('cleaned_data.xlsx', index=False)

# Challenge 2: Structuring Data

In this challenge, we will continue to work with customer data from an insurance company, but we will use a dataset with more columns, called marketing_customer_analysis.csv, which can be found at the following link:

https://raw.githubusercontent.com/data-bootcamp-v4/data/main/marketing_customer_analysis_clean.csv

This dataset contains information such as customer demographics, policy details, vehicle information, and the customer's response to the last marketing campaign. Our goal is to explore and analyze this data by performing data cleaning, formatting, and structuring.

In [10]:
mca_df = pd.read_csv("https://raw.githubusercontent.com/data-bootcamp-v4/data/main/marketing_customer_analysis_clean.csv")
mca_df

,unnamed:_0,customer,state,customer_lifetime_value,response,coverage,education,effective_to_date,employmentstatus,gender,...,number_of_policies,policy_type,policy,renew_offer_type,sales_channel,total_claim_amount,vehicle_class,vehicle_size,vehicle_type,month
0,0,DK49336,Arizona,4809.216960,No,Basic,College,2011-02-18,Employed,M,...,9,Corporate Auto,Corporate L3,Offer3,Agent,292.800000,Four-Door Car,Medsize,A,2
1,1,KX64629,California,2228.525238,No,Basic,College,2011-01-18,Unemployed,F,...,1,Personal Auto,Personal L3,Offer4,Call Center,744.924331,Four-Door Car,Medsize,A,1
2,2,LZ68649,Washington,14947.917300,No,Basic,Bachelor,2011-02-10,Employed,M,...,2,Personal Auto,Personal L3,Offer3,Call Center,480.000000,SUV,Medsize,A,2
3,3,XL78013,Oregon,22332.439460,Yes,Extended,College,2011-01-11,Employed,M,...,2,Corporate Auto,Corporate L3,Offer2,Branch,484.013411,Four-Door Car,Medsize,A,1
4,4,QA50777,Oregon,9025.067525,No,Premium,Bachelor,2011-01-17,Medical Leave,F,...,7,Personal Auto,Personal L2,Offer1,Branch,707.925645,Four-Door Car,Medsize,A,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10905,10905,FE99816,Nevada,15563.369440,No,Premium,Bachelor,2011-01-19,Unemployed,F,...,7,Personal Auto,Personal L1,Offer3,Web,1214.400000,Luxury Car,Medsize,A,1
10906,10906,KX53892,Oregon,5259.444853,No,Basic,College,2011-01-06,Employed,F,...,6,Personal Auto,Personal L3,Offer2,Branch,273.018929,Four-Door Car,Medsize,A,1
10907,10907,TL39050,Arizona,23893.304100,No,Extended,Bachelor,2011-02-06,Employed,F,...,2,Corporate Auto,Corporate L3,Offer1,Web,381.306996,Luxury SUV,Medsize,A,2
10908,10908,WA60547,California,11971.977650,No,Premium,College,2011-02-13,Employed,F,...,6,Personal Auto,Personal L1,Offer1,Branch,618.288849,SUV,Medsize,A,2
10909,10909,IV32877,California,6857.519928,No,Basic,Bachelor,2011-01-08,Unemployed,M,...,3,Personal Auto,Personal L1,Offer4,Web,1021.719397,SUV,Medsize,A,1

1. You work at the marketing department and you want to know which sales channel brought the most sales in terms of total revenue. Using pivot, create a summary table showing the total revenue for each sales channel (branch, call center, web, and mail).
Round the total revenue to 2 decimal points.  Analyze the resulting table to draw insights.

2. Create a pivot table that shows the average customer lifetime value per gender and education level. Analyze the resulting table to draw insights.

In [11]:
pivot_table = mca_df.pivot_table(values="total_claim_amount", index="sales_channel", aggfunc="sum").round(2).sort_values(by="total_claim_amount", ascending=False)
pivot_table

               total_claim_amount
sales_channel
Agent                  1810226.82
Branch                 1301204.00
Call Center             926600.82
Web                     706600.04

Agent channel brings the highest revenue, so agent sales are crucial. Since revenues are pretty evenly spread, a balanced strategy might be best.
Web and Call Center channels might need improvement though (better marketing).

## Bonus

You work at the customer service department and you want to know which months had the highest number of complaints by policy type category. Create a summary table showing the number of complaints by policy type and month.
Show it in a long format table.

*In data analysis, a long format table is a way of structuring data in which each observation or measurement is stored in a separate row of the table. The key characteristic of a long format table is that each column represents a single variable, and each row represents a single observation of that variable.*

*More information about long and wide format tables here: https://www.statology.org/long-vs-wide-data/*

In [12]:
mca_df['Month'] = pd.to_datetime(mca_df['effective_to_date']).dt.strftime('%B')
mca_df['Month']

0        February
1         January
2        February
3         January
4         January
           ...
10905     January
10906     January
10907    February
10908    February
10909     January
Name: Month, Length: 10910, dtype: object

In [13]:
complaints_table = mca_df.pivot_table(
    values="number_of_open_complaints",
    index=["Month", "policy_type"],
    aggfunc="count"
).reset_index()

complaints_table = complaints_table.sort_values(by=["Month", "number_of_open_complaints"], ascending=[True, False], ignore_index=True)

complaints_table

      Month     policy_type  number_of_open_complaints
0  February   Personal Auto                       3799
1  February  Corporate Auto                       1089
2  February    Special Auto                        204
3   January   Personal Auto                       4329
4   January  Corporate Auto                       1252
5   January    Special Auto                        237